export const FETCH_DIRECTORIES = 'FETCH_DIRECTORIES';
export const FETCH_DIRECTORIES_START = 'FETCH_DIRECTORIES_START';
export const FETCH_DIRECTORIES_FAIL = 'FETCH_DIRECTORIES_FAIL';
export const FETCH_DIRECTORIES_SUCCESS = 'FETCH_DIRECTORIES_SUCCESS';

export const CREATE_DIRECTORY = 'CREATE_DIRECTORY';
export const CREATE_DIRECTORY_START = 'CREATE_DIRECTORY_START';
export const CREATE_DIRECTORY_FAIL = 'CREATE_DIRECTORY_FAIL';
export const CREATE_DIRECTORY_SUCCESS = 'CREATE_DIRECTORY_SUCCESS';

export const TRIGGER_DIRECTORY_FOLD = 'TRIGGER_DIRECTORY_FOLD';
export const SELECT_DIRECTORY = 'SELECT_DIRECTORY';
export const PREVIEW_CREATE_DIRECTORY = 'PREVIEW_CREATE_DIRECTORY';
export const TRIGGER_CREATE_PREVIEW_OFF = 'TRIGGER_CREATE_PREVIEW_OFF';
