export const FETCH_DIRECTORIES = 'FETCH_DIRECTORIES';
export const FETCH_DIRECTORIES_START = 'FETCH_DIRECTORIES_START';
export const FETCH_DIRECTORIES_FAIL = 'FETCH_DIRECTORIES_FAIL';
export const FETCH_DIRECTORIES_SUCCESS = 'FETCH_DIRECTORIES_SUCCESS';
