export const FETCH_DIRECTORIES = 'FETCH_DIRECTORIES';
export const FETCH_DIRECTORIES_START = 'FETCH_DIRECTORIES_START';
export const FETCH_DIRECTORIES_FAIL = 'FETCH_DIRECTORIES_FAIL';
export const FETCH_DIRECTORIES_SUCCESS = 'FETCH_DIRECTORIES_SUCCESS';

export const CREATE_DIRECTORY_PREVIEW = 'CREATE_DIRECTORY_PREVIEW';
export const TRIGGER_CREATE_PREVIEW_OFF = 'TRIGGER_CREATE_PREVIEW_OFF';
export const CREATE_DIRECTORY = 'CREATE_DIRECTORY';
export const CREATE_DIRECTORY_START = 'CREATE_DIRECTORY_START';
export const CREATE_DIRECTORY_FAIL = 'CREATE_DIRECTORY_FAIL';
export const CREATE_DIRECTORY_SUCCESS = 'CREATE_DIRECTORY_SUCCESS';

export const EDIT_DIRECTORY_PREVIEW = 'EDIT_DIRECTORY_PREVIEW';
export const TRIGGER_EDIT_PREVIEW_OFF = 'TRIGGER_EDIT_PREVIEW_OFF';
export const EDIT_DIRECTORY = 'EDIT_DIRECTORY';
export const EDIT_DIRECTORY_START = 'EDIT_DIRECTORY_START';
export const EDIT_DIRECTORY_FAIL = 'EDIT_DIRECTORY_FAIL';
export const EDIT_DIRECTORY_SUCCESS = 'EDIT_DIRECTORY_SUCCESS';

export const DELETE_DIRECTORY_CONFIRM = 'DELETE_DIRECTORY_CONFIRM';
export const DELETE_DIRECTORY_CANCEL = 'DELETE_DIRECTORY_CANCEL';
export const DELETE_DIRECTORY = 'DELETE_DIRECTORY';
export const DELETE_DIRECTORY_START = 'DELETE_DIRECTORY_START';
export const DELETE_DIRECTORY_FAIL = 'DELETE_DIRECTORY_FAIL';
export const DELETE_DIRECTORY_SUCCESS = 'DELETE_DIRECTORY_SUCCESS';

export const TRIGGER_DIRECTORY_FOLD = 'TRIGGER_DIRECTORY_FOLD';
export const SELECT_DIRECTORY = 'SELECT_DIRECTORY';

export const FETCH_NOTICES = 'FETCH_NOTICES';
export const FETCH_NOTICES_START = 'FETCH_NOTICES_START';
export const FETCH_NOTICES_FAIL = 'FETCH_NOTICES_FAIL';
export const FETCH_NOTICES_SUCCESS = 'FETCH_NOTICES_SUCCESS';
